public enum Effect
{
    Health,
    Damage,
    Range,
    RotationSpeed,
    ReloadRate,
    BulletPierces,
    BulletAmount,
    BulletSpeed,
    BulletSpread,
    BulletLifetime,
    BulletTracking,
    BulletSticking,
    BulletExplosion,
    Discount,
    Power,
    Heat,
    CollectAmount,
    CollectRate,
    AutoStorage
}
